package compile

import (
	"fmt"
	"strings"

	"github.com/briceduke/ax/internal/core"
	"github.com/briceduke/ax/internal/version"
)

func applyHeader(rel string, data []byte, hash string) []byte {
	if strings.HasSuffix(strings.ToLower(rel), ".json") {
		return data
	}
	header := fmt.Sprintf("<!-- generated by ax. do not edit. input-hash: %s ax: %s -->\n\n", hash, version.Version)
	text := string(core.NormalizeLF(data))
	if !strings.HasPrefix(text, "---\n") {
		return []byte(header + text)
	}
	yamlBytes, body, err := core.SplitFrontmatter(data)
	if err != nil {
		return []byte(header + text)
	}
	out := "---\n" + string(yamlBytes) + "\n---\n\n" + header + body
	return []byte(out)
}
